### ISSUE TITLE
Voyager utility

### ISSUE THREAD

**Issue by chrkuo** [pachterlab/voyager#8]
thank you for creating this amazing tool - is it fair to assume that voyager is a replacement for analysis for spatial data like seurat/giotto. seems like there is a lot of inconsistencies with all the different package analyses out there.

**Comment by lambdamoses** [comment]
Maybe. Voyager actually doesn't replace everything that Seurat and Giotto do. Because SFE is based on SCE, I don't need to reimplement the non-spatial EDA functionalities in Seurat and Giotto because scater and scran already have the functionalities. It's more like bringing the geospatial tradition to the SCE ecosystem. Seurat itself doesn't do much in spatial analyses. Giotto at present has some methods for categorical spatial data that Voyager doesn't have. Since Bioconductor doesn't allow dependencies that are not on CRAN or Bioconductor, it would not be possible to incorporate many methods into Voyager. But I wish that more people take interoperability seriously so it won't be necessary to incorporate the methods.
